const data = [
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-10760-p4cei5oq4p2n2zl6.jpg",
    title: "קובה סלק פיקנטית ברוטב סמיך",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/10760",
    recipeDescription:
      "קובה סלק במלית בשר מהמטבח העיראקי בסגנון פיקנטי וברוטב אדום מושלם - ארוחת צהריים מבושלת פשוט טעימה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-10746-jemadvm5fvts8zxn.jpg",
    title: "פוקאצ'ת סביח מטורפת",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/10746",
    recipeDescription:
      "פוקאצ'ת סביח שבטוח תאמצו - פוקאצ'ה מבצק שמרים נפלא בתוספת ביצים קשות, חצילים מטוגנים, ירקות והרבה טחינה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-10242-RNpOgvJOcYZuviwI.jpg",
    title: "קובה בורגול מטוגנת עם בשר טחון",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/10242",
    recipeDescription: "קובה בורגול עיראקית מטוגנת שכולם אוהבים במילוי בשר בקר טחון וצנוברים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-10077-pIDJzhZZbFmPzfpw.jpg",
    title: "כעכ עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/10077",
    recipeDescription: "כעכ (או כעכת/קעקעת) מהמטבח העיראקי המושלם - מאפה שמרים נהדר עם חוויאג' לאפייה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-10071-qf3SYmzZdH7E1V1H.jpg",
    title: "ערוק בלחם - קציצות בשר מהמטבח העיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/10071",
    recipeDescription: "קציצות ערוק עיראקיות שכיף להגיש כסנדוויץ' בתוך לחם עם עמבה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9820-aMnBMHtplmQKJw4a.jpg",
    title: "קובה פתתה כשרה לפסח",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9820",
    recipeDescription: "קובה פתתה עיראקית כשרה לפסח ממעטפת פירה תפוחי אדמה ומילוי בשר בקר טחון",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9739-F5LykIpvD4WOWiiA.jpg",
    title: "חלבה עיראקית",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9739",
    recipeDescription:
      'חלבה עיראקית מיוחדת, מתוקה וכמובן ששונה מהחלבה הרגילה שכולנו מכירים - אגב, הפירוש של המילה חלבה בערבית היא "ממתק" והקינוח הזה עונה במדויק על ההגדרה הזו',
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9730-CuLlFbP1qNtWDkKX.jpg",
    title: "פלאו בג'יג' עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9730",
    recipeDescription: "תבשיל שוקי עוף עם אורז אדום עיראקי - מנה מושלמת לארוחת הצהריים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9711-ijWkw4kANLzh4hhA.jpg",
    title: "פלאו אחמר צמחוני",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9711",
    recipeDescription:
      "פלאו אחמר בג'יג' עיראקי - מתכון עיראקי מנצח לאורז אדום רק ללא העוף שמתלווה אליו במתכון המקורי (מתאים גם לטבעוניים)",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9703-ZUFmGiBIFb4MDrpS.jpg",
    title: "סמבוסק בג'בן",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9703",
    recipeDescription: "סמבוסק במילוי גבינה מהמטבח העיראקי המפורסם - מומלץ לאכול ישר מהתנור!",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9696-icblmVn8bEkE6Y7S.jpg",
    title: "סמבוסק בטאווה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9696",
    recipeDescription:
      "סמבוסק במילוי חומוס שנקרא גם סמבוסק בטאווה מהמטבח העיראקי המושלם - ניתן גם לטגן וגם לאפות בתנור!",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9697-DsifrIjAs8VnzPsM.jpg",
    title: "סמבוסק אגוזים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9697",
    recipeDescription: "סמבוסק חילו (סמבוסק במילוי אגוזים) מהמטבח העיראקי - סמבוסק מפנק עם שקדים, אגוזים ומי ורדים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9652-5bURBQuJqjXhafXM.jpg",
    title: "אורז עם עדשים בסגנון עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9652",
    recipeDescription: "קיצ'רי בגרסא מיוחדת (ללא עגבניות) אלא עם עדשים כתומות, שום וכמון",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9631-KTXXqy4EOExW8drO.jpg",
    title: "טורשי עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9631",
    recipeDescription: 'ירקות כבושים מהמטבח העיראקי הנקראים גם "טורשי" - תמיד טוב שיש במקרר בבית!',
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9604-x4s6CbT2BGFGStEY.jpg",
    title: "קובה בורגול מטוגנת",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9604",
    recipeDescription:
      "קובה בורגול עיראקית מטוגנת בשמן עמוק עם מעטפת של בורגול וסולת ובמלית בשר בקר טחון עם בצל, פטרוזיליה ותבלינים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9412-OdN7RTvFWVNuZG8v.jpg",
    title: "עג'ה בג'בן",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9412",
    recipeDescription: "לביבות גבינה עיראקיות מטוגנות הנקראות גם עג'ה או עיג'ה בג'בן (גבינה בעיראקית)",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9409-dZYwlqHaJU3MBJ48.jpg",
    title: "קאהי עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9409",
    recipeDescription: "קאהי מהמטבח העיראקי - מאפה מטוגן עם חמאה וסוכר מעל",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9357-O4lWIw1M3mMIe3mE.jpg",
    title: "ערוק - לביבות ירק עיראקיות",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9357",
    recipeDescription:
      "תמיד שמעתם על ערוק (או עיג'ה) ולא ידעתם איך להכין? הגיע הזמן שתכירו את הגרסא של רוחל'ה ללביבות הירק העיראקיות הכי מפורסמות שיש. קבלו מתכון לערוק מהמטבח העיראקי עם פירה תפוחי אדמה, פטרוזיליה, בצל...",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-9142-mBkfK6LFv1Nz2oaA.jpg",
    title: "סלונה טופו",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/9142",
    recipeDescription:
      "תבשיל חמוץ מתוק בסגנון דג עיראקי - את המאכל הזה כיף מאוד להכין לסעודת חג, הוא מוכר בטעמו החמוץ-מתוק הייחודי שנשמר גם בגרסה הטבעונית! האורחים ייהנו מהחידוש שבדבר, ההכנה עצמה לא מסובכת והטעם, כמובן,...",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-8997-0fcnkcn4HLwn2r2f.jpg",
    title: "קובה סלק במעטפת סולת",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/8997",
    recipeDescription: "קובה סלק ביתית במילוי בשר בקר טחון עם בצל וכוסברה - מתאים מאוד לימי חורף קשים במיוחד",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-8818-7gMl0d5uU5gv5AxB.jpg",
    title: "סהרוני סמבוסק גבינה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/8818",
    recipeDescription: "סמבוסק במילוי גבינה מלוחה - מאפים טעימים במיוחד מהמטבח העיראקי המתאימים לאירוח המשפחה והחברים!",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-8828-AaRAhcTGaLYwUVCR.jpg",
    title: "סמבוסק חומוס מטוגן",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/8828",
    recipeDescription: "סהרוני סמבוסק חומוס מטוגנים מהמטבח העיראקי הנהדר - טעמים מזרחיים עשירים בבצק מושלם",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-8697-5ZPs4f2Q7TU3ANV6.jpg",
    title: "עמבה ביתית",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/8697",
    recipeDescription:
      "לא יודעים איך מכינים עמבה ביתית? קבלו מתכון של עמבה עיראקית אסלית עם חתיכות מנגו כמו שהעיראקים אוהבים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-8628-khjd3hX3Y8d4XkKd.jpg",
    title: "לוזינה תפוזים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/8628",
    recipeDescription: "ממתק לוזינה מתפוזים (במקום חבושים) המתבסס על הממתק העיראקי המפורסם",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-8032-TupvobDts7j2O5iA.jpg",
    title: "תבשיל לבבות עוף עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/8032",
    recipeDescription: "תבשיל לבבות עוף פיקנטי מהמטבח העיראקי העשיר בתוספת בצל, פלפל אדום, תפוחי אדמה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7897-Y5xWw2XxYjgz0AJz.jpg",
    title: "קובה מצה מטוגנת",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7897",
    recipeDescription: "קובה מצה מיוחדת לפסח במילוי בשר, בצל, פטרוזיליה וצנוברים - המנה העיקרית המנצחת שלכם בחג",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7830-1C84DBXfmKqB7i6H.jpg",
    title: "סמבוסק גבינות וזעתר",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7830",
    recipeDescription: "סמבוסק מיוחד וטעים מבצק זעתר נפלא במלית תערובת גבינות מלוחה ובציפוי זעתר ושומשום",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7626-woFqZzzimpTm6Hbl.jpg",
    title: "כיסוני גבינה עיראקיים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7626",
    recipeDescription:
      "כיסונים מבצק פריך במילוי גבינות וציפוי שומשום מהמטבח העיראקי המושלם - נקראים גם סמבוסק גבינה כמובן",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7531-5heDvhiUoAVyCHgZ.jpg",
    title: "פלאו בג'יג'",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7531",
    recipeDescription:
      "תבשיל פלאו בג'יג' (נקרא גם פלאו בג'יג'י) מהמטבח העיראקי המפורסם המורכב מכרעי עוף מבושלים באורז אדום עם עגבניות ובצל",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7485-IygPFJHbF6PNUn6N.jpg",
    title: "סמבוסק עיראקי במילוי חומוס",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7485",
    recipeDescription: "סמבוסק מהמטבח העיראקי מטוגן בשמן עמוק במילוי גרגירי חומוס עם בצל וכמון ומבצק דק וקריספי במיוחד",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7464-Qywr6RWEKHLgcYbp.jpg",
    title: "לוזינה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7464",
    recipeDescription:
      "ממתק חבושים שנקרא גם לוזינה מהמטבח העיראקי המושלם - מתאים מאוד לחינה, מימונה ושאר אירועים שמחים ומתוקים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7329-o1DFPknviJjkLp8B.jpg",
    title: "קעקעת עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7329",
    recipeDescription: "קעקעת מושלמים מהמטבח העיראקי עם חוואיג' לאפייה שמזכירים את ניחוחות העבר",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7311-vWVKepcd7HnvbMWD.jpg",
    title: "מחמוסה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7311",
    recipeDescription:
      "תבשיל עיראקי טעים ומיוחד עם חזה עוף, תפוחי אדמה, עגבניות ובצל - אוכל שמזכיר את נשכחות העבר מעיראק",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7062-G4WYNKhifxKOm5FD.jpg",
    title: "סמבוסק עם חומוס",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7062",
    recipeDescription:
      "סמבוסק עיראקי מטוגן במילוי גרגירי חומוס מבושלים עם בצל ותבלינים - אחד ממנות הדגל העיראקיות הטעימות ביותר",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7018-xUu5fo6rcf4FJDwV.jpg",
    title: "קובה סלק עיראקית",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7018",
    recipeDescription:
      "קובה סלק עיראקית מושלמת במילוי בשר בקר טחון בטעם חמוץ-מתוק ממכר במיוחד - המנה הראשונה הכי טעימה לארוחה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-7014-ReOL14C0AGS5lzaz.jpg",
    title: "זינגולה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/7014",
    recipeDescription:
      "שבלולי בצק קריספיים מהמטבח העיראקי המפורסם טבולים בסירופ סוכר מפנק - מתוקים שמתאימים מאוד לאירועי מימונה וחינה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6972-AGl6V4xlFOYaG2HJ.jpg",
    title: "מלפפונים בכבישה ביתית",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6972",
    recipeDescription: "מלפפונים חמוצים בכבישה ביתית טעימה במיוחד עם שמיר, חומץ ומלח - תוספת נפלאה לכל ארוחה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6875-nNKWHW8cHNMU0h7o.jpg",
    title: "סמבוסק חילו",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6875",
    recipeDescription: "סמבוסק חילו מתוק מהמטבח העיראקי במילוי ממרח תמרים עם שקדים, אגוזים וקוקוס",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6744-2OJwgNjlqBCnUwTC.jpg",
    title: "סלונה - שכבות חצילים ודגים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6744",
    recipeDescription: "גרסא טעימה של סלונה מהמטבח העיראקי עם חצילים, עגבניות ופרוסות דגים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6648-HcNG4rvKgC4yRWyj.jpg",
    title: "לפת כבושה במלח",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6648",
    recipeDescription:
      "לפת כבושה במלח וחומץ בתוספת סלק אדום שמעניק לה את הצבע האדום הנהדר - לפת חמוצה מהמטבח העיראקי המסורתי",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6589-loWdPyLGad1xKmEo.jpg",
    title: "מנת סביח בצלחת",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6589",
    recipeDescription:
      "סביח טעים ביותר שמוגש בצלחת הגשה עם ביצים קשות, חצילים מטוגנים, סלט ירקות, טחינה ובתוספת פטריות שמפיניון",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6466-q5qLAZjBEmjEtaKd.jpg",
    title: "לפת מבושלת של העיראקים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6466",
    recipeDescription:
      "קינוח חם ומתוק מלפת מבושלת (שלרם מהמטבח העירקי) עם שקיקי תה וסוכר - מעדן עיראקי של יום שבת קריר",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6415-5ey7s8tWQtYrL4QL.jpg",
    title: "קובה אורז במילוי דג",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6415",
    recipeDescription:
      "קובה סמק (דגים) מהמטבח העיראקי המפורסם - קובה מטוגנת במעטפת אורז במילוי פילה דג בקלה מפורר עם פטרוזיליה, בצל ותבלינים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6348-8b05ztPVaFhbQU3s.jpg",
    title: "סמבוסק חומוס עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6348",
    recipeDescription: "סמבוסק חומוס מטוגן מהמטבח העיראקי - מלית טעימה ביותר של גרגירי חומוס טחונים עם בצל ותבלינים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6315-aiauj7VRBecQCwiL.jpg",
    title: "כעכעת - כעכים עיראקים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6315",
    recipeDescription: "כעכים עיראקים מבצק שמרים עם חוואייג' אפייה - מיוחדים, טעימים וקלים להכנה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6239-aJY9JqOp2uNukOZx.jpg",
    title: "חמוצים עיראקים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6239",
    recipeDescription:
      "חמוצים בסגנון עיראקי שנקראים גם טורשי - מגוון רחב של ירקות כמו מלפפונים, כרובית, גזר, קישואים ופלפלים כבושים בחומץ עם נגיעות בהרט של עמבה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6225-9kzeNEMb2rsSaJKP.jpg",
    title: "סנדוויץ' קציצת ירק עיראקית (עיג'ה) משודרג",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6225",
    recipeDescription: "קציצת ירק עיראקית (עיג'ה) משודרגת ואפויה בתנור בכריך נפלא עם ירקות אנטיפסטי וחציל מטוגן",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-6038-xn0Bt167hxn34FdZ.jpg",
    title: "שום פרסי כבוש",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/6038",
    recipeDescription: "שום עג'מי - שום כבוש בחומץ ומלח מהמטבח העיראקי האורגינל",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-5837-sBbJx5k3tWyp3tsT.jpg",
    title: "חצילים עיראקים מטוגנים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/5837",
    recipeDescription: "פרוסות חצילים מטוגנות עם הקליפה בסגנון עיראקי של פעם",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-5710-zRNQ62EItBsO6zbN.jpg",
    title: "מלפפונים חמוצים ביתיים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/5710",
    recipeDescription: "מלפפונים חמוצים במלח תוצרת בית עם שמיר ושום",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-5463-XObn9yx3IdP4y3Bj.jpg",
    title: "קובה פטטה עיראקית",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/5463",
    recipeDescription: "קובה פטטה מטוגנת במילוי בשר בקר טחון עם פטרוזיליה וצנוברים מהמטבח העיראקי",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-5462-nosRIACTaZmbAcXv.jpg",
    title: "קובה בורגול מבושלת",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/5462",
    recipeDescription: "קובה בורגול במילוי בשר בקר טחון עם צנוברים וצימוקים מבושלת במי כורכום",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-5384-vZSqKfpC8u9auRDh.jpg",
    title: "קובה אורז מטוגנת",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/5384",
    recipeDescription: "קובה אורז מטוגנת מהמטבח העיראקי עם מעטפת אורז וחזה עוף טחון ומילוי בשר בקר טחון",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-5238-2ah64mivgusJFUAi.jpg",
    title: "כעכת של עיראקים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/5238",
    recipeDescription: "כעכת עיראקי טעים ביותר בהכנה ביתית קלה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-5151-D9RoGkrIjxO5p4Ze.jpg",
    title: "חרוסת עיראקית",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/5151",
    recipeDescription: "חרוסת של עיראקים - סילאן עם בוטנים ושקדים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-5144-3G4UeRzQqed1XW6o.jpg",
    title: "עוגיות בעבע עירקיות",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/5144",
    recipeDescription: "עוגיות בעבע בנוסח יהדות עירק במילוי תמרים עם קינמון",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-5107-J2WXpAIsGLF1KEjH.jpg",
    title: "זנגולה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/5107",
    recipeDescription: "עוגיות ספירלה מטוגנות בשמן עמוק עם סירופ סוכר ודבש",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-4924-4JnS4z9G7xTqyZHK.jpg",
    title: "חצילים מטוגנים למנת סביח",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4924",
    recipeDescription: "פרוסות חצילים מטוגנות במיוחד להכנת מנת סביח עיראקי",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-4857-eJgbtVmPR1fuSfOb.jpg",
    title: "ערוק",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4857",
    recipeDescription: 'פשטידות ירק הנקראות "ערוק" מהמטבח העיראקי המפורסם',
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-4815-nYOBCkclXu4fH0xl.jpg",
    title: "כרובית כבושה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4815",
    recipeDescription: "כרובית כבושה צהובה בחומץ ואבקת קארי",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-4682-rlGyg9TJ1yx5q7qc.jpg",
    title: "קובה במיה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4682",
    recipeDescription: "קובה במיה עיראקית במילוי בשר וצנוברים במרק אדום עם עגבניות",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-4678-HNfR36U5TfUMuajX.jpg",
    title: "קובה בורגול עיראקית",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4678",
    recipeDescription: "קובה בורגול וסולת מהמטבח העיראקי במילוי בשר בקר טחון",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-4512-8d5LfEYIpjQWEYmi.jpg",
    title: "שיפטה עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4512",
    recipeDescription: "קציצות בשר מהמטבח העיראקי במרק אדום עם תפוחי אדמה ואפונה ירוקה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-4484-10b0vtntger8ougi.jpg",
    title: "פלפלים חריפים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4484",
    recipeDescription: "פלפלים ירוקים חריפים וביתיים בחומץ, מלח ואבקת קארי חמוצים - הפלפלים החריפים הכי טעימים שתאכלו!",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-4185-D5GxTwi6PW.jpg",
    title: "סנדוויץ' סביח",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4185",
    recipeDescription: "סביח בפיתה עם חצילים, טחינה ועמבה - באדיבות השף גילי חיים ל הלמנ'ס המציעה מגוון ממרחים ורטבים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-4114-9C6aW2XKZj.jpg",
    title: "רולדות סביח",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4114",
    recipeDescription: "סביח בבצק עלים במקום בפיתה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-4100-h3nxOiMxoD.jpg",
    title: "סמבוסק טונה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/4100",
    recipeDescription: "סמבוסק ביתי במילוי טונה וביצה קשה - מאפה נהדר לפתוח איתו את הבוקר",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-3451-PTmNjd4rpaOxZi5W.jpg",
    title: "בעבע בתמר",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/3451",
    recipeDescription: "עוגיות תמרים עירקיות בציפוי שומשום - הכי טעימות עם כוס תה או קפה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-3414-pGvS4tmRkF.jpg",
    title: "מרק קובה סלק",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/3414",
    recipeDescription: "מרק סלק אדום עם קובות במילוי בשר טחון - מעדן מהמטבח העיראקי המצוין",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-3289-dWt026Vflt.jpg",
    title: "טבית עירקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/3289",
    recipeDescription: "טבית עירקי חם וטעים לשבת",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-2673-tBRGPgXSpT.jpg",
    title: "סמבוסק בשר",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/2673",
    recipeDescription: "סמבוסק עם מילוי של בשר בקר טחון ובצל מטוגן או אפוי לבחירה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-2659-dxuAJpAarI.JPG",
    title: "סמבוסק גבינה מקמח מלא",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/2659",
    recipeDescription: "סמבוסק במילוי גבינה מקמח מלא בשילוב קמח לבן (מתכון מלפני המהפך הטבעוני שלי)",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-2568-Mt6n86qwrL.jpg",
    title: "קובה מטוגנת",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/2568",
    recipeDescription: "קובה מטוגנת במילוי בשר בקר טחון, צנוברים ותבלינים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-2560-6IMSFHqbae.JPG",
    title: "מרק קובה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/2560",
    recipeDescription: "מרק ירקות עם קובה סולת במילוי בשר בקר טחון ותבלינים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-2277-l6BlDr2OEW8n3EPY.jpg",
    title: "לפת כבושה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/2277",
    recipeDescription: "מעדן נפלא לליווי כל ארוחה מהמטבח העיראקי - תמיד טוב שיש בבית!",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-2210-Ikwp3uo0TD.jpg",
    title: "מג'דרה עם אורז מלא",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/2210",
    recipeDescription: "אורז מלא עם עדשים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-2075-UMWHeoQ2ti.jpg",
    title: "מרק שורבה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/2075",
    recipeDescription: "מרק שורבה - מרק עם אורז",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-2052-f0lYTVT7erioAyqf.jpg",
    title: "מלפפונים חמוצים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/2052",
    recipeDescription: "מלפפונים חמוצים במלח",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-1960-I4GIethy92Rt0rPl.jpg",
    title: "קובה אדומה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/1960",
    recipeDescription: "מרק קובה סלק אדומה מהמטבח העיראקי במילוי בשר בקר טחון - מעדן שמתאים למנה הראשונה בארוחה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-1686-3nxOiMxoDo.jpg",
    title: "סמבוסק עם גבינה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/1686",
    recipeDescription: "מאפה מבצק פריך במילוי גבינה (מתכון מלפני המהפך הטבעוני שלי)",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-1684-3z47t4mEFX.jpg",
    title: "קובה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/1684",
    recipeDescription: "קובה ממולאת בבשר (מתכון מלפני המהפך הטבעוני שלי)",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-1447-HV39E6TLKV.JPG",
    title: "עוף ברסק עגבניות",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/1447",
    recipeDescription: "מאכל עיראקי אותנטי של כרעי עוף ברסק עגבניות ואורז",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-943-BAQNy7LBEl.jpg",
    title: "סביח עיראקי",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/943",
    recipeDescription: "כריך סביח",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-753-Y0GJLKPLyQ.JPG",
    title: "סמבוסק במילוי חומוס",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/753",
    recipeDescription: "כיסוני החומוס המוכרים מהמטבח העיראקי",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-713-tYQujcl9CH.jpg",
    title: "קובה צהובה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/713",
    recipeDescription: "קובה צהובה במרק",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/Recipe-710-1ZrCsHCOp8.jpg",
    title: "אורז אדום עם פול",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/710",
    recipeDescription: "אורז אדום בנוסח עיראקי עם פול טרי",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-704-1FX6qQXIHWwr07yE.jpg",
    title: "מלפוף",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/704",
    recipeDescription: "מלפוף עיראקי - בצק פילו ממולא בוטנים ושקדים טחונים עם סירופ סוכר מתוק",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-688-4R2r0Pc2rOQxXV61.jpg",
    title: "קבבים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/688",
    recipeDescription: "קבבים עיראקיים טעימים וקלים להכנה באפייה ביתית בתנור עם בצל, פטרוזיליה, שום ותבלינים",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-464-UX3cnVHsYFrJGKno.jpg",
    title: "קובה אורז",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/464",
    recipeDescription: "קובה אורז עיראקית מטוגנת במילוי חזה עוף טחון ובצל",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://storage.googleapis.com/st2.foodsd.co.il/Images/recipes-thumbnails/xxl.webp",
    title: "פולים עם שום, כמון ותבלינים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/512",
    recipeDescription: "פולים של דליה וענונו",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-295-IJtIwiB4VEBS4UHc.jpg",
    title: "לפת חמוץ (מח'ללה)",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/295",
    recipeDescription: "לפת בחומץ ומלח בצבע אדום-סגול נפלא שהוא מקבל משילוב סלק - חמוצים עיראקיים במיטבם",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://storage.googleapis.com/st2.foodsd.co.il/Images/recipes-thumbnails/xxl.webp",
    title: "טביט",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/460",
    recipeDescription: "חמין עיראקי",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-435-0g8GlKPRxqtIlR0O.jpg",
    title: "פיתות ביתיות",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/435",
    recipeDescription: "פיתות ביתיות טעימות וקלות להכנה עשויות במחבת שכיף לאכול ישר אחרי הטיגון",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-254-qhMZSEcdIOHRmwym.jpg",
    title: "סמבוסק חומוס",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/254",
    recipeDescription: "כיסונים עיראקיים ממולאים בגרגירי חומוס טחונים עם בצל מטוגן",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-339-kUZwNIyaDPYmqBgB.jpg",
    title: "כעכים מתוקים",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/339",
    recipeDescription: "כעכים מתוקים מהמטבח העיראקי הנקראים גם כעכעת - מושלמים עם הקפה",
    origin: "עיראקי",
  },
  {
    imageUrl: "https://st1.foodsd.co.il/Images/Recipes/xxl/Recipe-226-wEyPRWU0hUtaVNY4.jpg",
    title: "קובה תפוח אדמה",
    recipeUrl: "https://www.foodsdictionary.co.il/Recipes/226",
    recipeDescription: "קובה תפוח אדמה מטוגנת במילוי חזה עוף וצימוקים - אחת הקובות העיראקיות המוצלחות והטעימות ביותר",
    origin: "עיראקי",
  },
];
